### PR TITLE
Added google_analytics_key to template and example config

### PR DESCRIPTION
**Pull request by yasthil**
- Added google_analytics_key as part of the default template config

### CODE REVIEW

**Comment by yasthil** [comment]
@jamesjypark I was wondering that too when I added the GA key.
However, I did see within `default.html` there's some script tags that handles the setup and firing of pageviews. 
If I'm not mistaken, this should fire on each page already.

**Comment by jamesjypark** [comment]
@yasthil Good point, I think the code in `default.html` should be doing what we want. Do you think you'll be able to run the site locally (if you haven't already) and make sure that the `pageview` event is being hit? If you go to Google Analytics console > `Reports` > `Realtime` > `Overview`, you can see the `pageview` events fire in real time.

**Comment by yasthil** [comment]
Hey @jamesjypark!
Thanks for the feedback. The Google Analytics code is surrounded by a check to see if the code is running in production and has a google_analytics_key. To test if any pageviews were being sent, I removed this check and tested locally - they are been sent. I've added the conditional back so it should be good, but we should test this on the QA environment thoroughly. 

I'm having an issue building using the latest develop. Will chat to @wsonnex and once I've merged develop back in here, I'll update this PR.
Thanks again :)

**Comment by jamesjypark** [comment]
@yasthil I agree, we'll probably want to test in QA before it goes live.
I also don't have access to the GA console, maybe you could ask @dan-bcc3d?

Let me know if there is anything I can help with!
Thanks :)

**Comment by yasthil** [comment]
Thanks @jamesjypark!
I have messaged Dan on Slack - but that may have been the wrong Dan :| 
@dan-bcc3d  - let me know if you get a chance to look at the GA account and verify if the hits are coming through as expected.

@jamesjypark I've merged in with develop and confirmed (on local build) the pageviews are being sent.

**Comment by dan-bcc3d** [comment]
That was not the right Dan on Slack :)

I do not see any activity on the analytics

**Comment by yasthil** [comment]
Hi @dan-bcc3d! :) 
Apologies for the confusion, think there's a few Dan's on our slack group.

Just to confirm, I'm using `UA-162929587-1` as the tracking ID.
[GA_Hits.pdf](https://github.com/bccovid-19/track/files/4552027/GA_Hits.pdf)

Please find the attached export from the Google Tag Assistant extension below. It shows that the site fired a few pageviews successfully. Let me know if anything is looking incorrect.
(Ignore the other tracking ID `UA-5577581-4` - that was fired when I clicked on the GoFundMe page)

**Comment by chaosaffe** [comment]
Can confirm the tracking ID and see the hits on the 28th.

**Pull request merged**
